CC = gcc -g

RM = rm -f

CFLAGS += -I./include -Wall -Wextra
LDFLAGS =

NAME = server

SRCS 	= 	src/common/linked_list/linked_list_add.c				\
		src/common/linked_list/linked_list_get.c				\
		src/common/linked_list/linked_list_delete.c				\
		src/common/linked_list/linked_list_create.c				\
		src/common/linked_list/linked_list_conditional.c			\
		src/common/linked_list/linked_list_basic.c				\
		src/common/linked_list/linked_list_advanced.c				\
		src/common/linked_list/list_clean.c					\
		src/common/arg_parser/arg_parser_cleanup.c				\
		src/common/arg_parser/arg_parser_initalisation.c			\
		src/common/arg_parser/argument_regex.c					\
		src/common/arg_parser/parse_arguments.c					\
		src/common/socket/socket_cleanup.c					\
		src/common/socket/socket_initialisation.c				\

OBJDIR = obj

OBJS = $(SRCS:%.c=$(OBJDIR)/%.o)

NB_SRCS := $(words $(SRCS))
COMPILATION_INDEX := 1

$(OBJDIR)/%.o : %.c
	@if [ "$(CC)" != "gcc" ] && [ "$(COMPILATION_INDEX)" = "1" ]; then printf "%b" "\033[1;31mWarning Debug Flag\033[0m\n";fi
	@printf "%b" "\033[1;32m[$(COMPILATION_INDEX)/$(NB_SRCS)]\033[0m "
	@printf "%b" "\033[0;32mBuilding C object $@\033[0m\n"
	@$(eval COMPILATION_INDEX=$(shell echo $$(($(COMPILATION_INDEX)+1))))
	@mkdir -p $(OBJDIR)
	@mkdir -p $(@D)
	@$(CC) -c $< -o $@ $(CFLAGS)

all: $(NAME)

$(NAME): $(OBJS)
	@printf "%b" "\033[1;32mLinking C executable $(NAME)\033[0m\n"
	@$(CC) $(OBJS) $(CFLAGS) -o $(NAME) $(LDFLAGS)
clean:
	@printf "%b" "\033[0;32mRemove C objects\033[0m\n"
	@$(RM) $(OBJS)
	@$(RM) -r $(OBJDIR)

fclean: clean
	@printf "%b" "\033[0;32mRemove C executable\033[0m\n"
	@$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re

