CC = gcc -g

RM = rm -f

CFLAGS += -I./include -Wall -Wextra
LDFLAGS =

NAME = server

SRCS =	src/common/arg_parser/arg_parser_cleanup.c		\
	src/common/arg_parser/arg_parser_initialisation.c	\
	src/common/arg_parser/argument_regex.c			\
	src/common/arg_parser/parse_arguments.c			\
	src/common/circular_buffer/circbuff.c			\
	src/common/circular_buffer/circbuff_buf.c		\
	src/common/circular_buffer/circbuff_file.c		\
	src/common/circular_buffer/circbuff_print.c		\
	src/common/circular_buffer/circbuff_strings.c		\
	src/common/circular_buffer/circbuff_utils.c		\
	src/common/command_parser/command_parser.c		\
	src/common/linked_list/linked_list_add.c                \
	src/common/linked_list/linked_list_get.c		\
        src/common/linked_list/linked_list_delete.c		\
	src/common/linked_list/linked_list_create.c		\
	src/common/linked_list/linked_list_conditional.c	\
	src/common/linked_list/linked_list_basic.c		\
	src/common/linked_list/linked_list_advanced.c		\
	src/common/linked_list/list_clean.c			\
	src/common/map/map_create.c				\
	src/common/map/map_free.c				\
	src/common/map/map_print.c				\
	src/common/map/map_str_to_tile.c			\
	src/common/map/map_vector.c				\
	src/common/socket/socket_cleanup.c			\
	src/common/socket/socket_initialisation.c		\
	src/server/ai_commands/broadcast.c			\
	src/server/ai_commands/connect_nbr.c			\
	src/server/ai_commands/eject.c				\
	src/server/ai_commands/fork.c				\
	src/server/ai_commands/forward.c			\
	src/server/ai_commands/incantation.c			\
	src/server/ai_commands/inventory.c			\
	src/server/ai_commands/left.c				\
	src/server/ai_commands/look.c				\
	src/server/ai_commands/right.c				\
	src/server/ai_commands/set.c				\
	src/server/ai_commands/take.c				\
	src/server/connection/poll_accept.c			\
	src/server/connection/poll_cleanup.c			\
	src/server/connection/poll_initialisation.c		\
	src/server/connection/poll_loop.c			\
	src/server/graphic_commands/bct.c			\
	src/server/graphic_commands/mct.c			\
	src/server/graphic_commands/msz.c			\
	src/server/graphic_commands/pln.c			\
	src/server/graphic_commands/plv.c			\
	src/server/graphic_commands/ppo.c			\
	src/server/graphic_commands/sgt.c			\
	src/server/graphic_commands/sst.c			\
	src/server/graphic_commands/tna.c			\
	src/server/team/team_action.c				\
	src/server/team/team_cleanup.c				\
	src/server/team/team_initialisation.c			\
	src/server/team/team_search.c				\
	src/server/user/user_action.c				\
	src/server/user/user_cleanup.c				\
	src/server/user/user_get.c				\
	src/server/user/user_initialisation.c			\
	src/server/user/user_quit.c				\
	src/server/user/user_search.c				\
	src/server/main.c					\
	src/server/server_cleanup.c				\
	src/server/server_initialisation.c			\
	src/server/server_loop.c				\

OBJDIR = obj

OBJS = $(SRCS:%.c=$(OBJDIR)/%.o)

NB_SRCS := $(words $(SRCS))
COMPILATION_INDEX := 1

$(OBJDIR)/%.o : %.c
	@if [ "$(CC)" != "gcc" ] && [ "$(COMPILATION_INDEX)" = "1" ]; then printf "%b" "\033[1;31mWarning Debug Flag\033[0m\n";fi
	@printf "%b" "\033[1;32m[$(COMPILATION_INDEX)/$(NB_SRCS)]\033[0m "
	@printf "%b" "\033[0;32mBuilding C object $@\033[0m\n"
	@$(eval COMPILATION_INDEX=$(shell echo $$(($(COMPILATION_INDEX)+1))))
	@mkdir -p $(OBJDIR)
	@mkdir -p $(@D)
	@$(CC) -c $< -o $@ $(CFLAGS)

all: $(NAME)

$(NAME): $(OBJS)
	@printf "%b" "\033[1;32mLinking C executable $(NAME)\033[0m\n"
	@$(CC) $(OBJS) $(CFLAGS) -o $(NAME) $(LDFLAGS)
clean:
	@printf "%b" "\033[0;32mRemove C objects\033[0m\n"
	@$(RM) $(OBJS)
	@$(RM) -r $(OBJDIR)

fclean: clean
	@printf "%b" "\033[0;32mRemove C executable\033[0m\n"
	@$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re

